---
- name: Move ssh key from variable to file
  tags: [localhost-ssh]
  become: false
  delegate_to: localhost
  run_once: true
  block:
    - name: Check constraints
      ansible.builtin.assert:
        that:
          - ansible_ssh_private_key

    - name: Create secret directory
      ansible.builtin.file:
        path: "{{ ansible_ssh_private_key_file | dirname }}"
        mode: 0700
        state: directory

    - name: Copy ssh key
      ansible.builtin.copy:
        content: "{{ ansible_ssh_private_key }}\n"
        dest: "{{ ansible_ssh_private_key_file }}"
        mode: 0600
