{{- with .Values.postgresBackuper -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "postgres-backuper.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
data:
  {{- range $k, $v := .secretValues }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end -}}
